Build from snapcraft.yaml and use ucdev PPA
snapcore/pc-amd64-gadget pull request #66
Opened 2022-08-01 13:56 UTC by alfonsosanchezbeato

Remove makefile and do special steps from an override-build section
instead.

Take now signed grub and shim form the ucdev/uc-staging-ppa PPA, using
package-repositories. Now we use epochs in the version of
grub-efi-amd64-signed and shim-signed packages, so the build should
always take the ones from the PPA instead of those in the archive, as
2:<version> will always be greater than the package version in the
latter. Nonetheless, do an additional static check for this.

Forward-ported from https://github.com/snapcore/pc-amd64-gadget/pull/65

2022-08-01 14:02 UTC, alfonsosanchezbeato commented
Note that this will not build until we have jammy binaries in https://launchpad.net/~ucdev/+archive/ubuntu/uc-staging-ppa.

2022-08-01 15:08 UTC, vorlonofportland commented
> Note that this will not build until we have jammy binaries in https://launchpad.net/~ucdev/+archive/ubuntu/uc-staging-ppa.

Those binaries are there as of yesterday..

2022-08-01 15:14 UTC, alfonsosanchezbeato commented
> > Note that this will not build until we have jammy binaries in https://launchpad.net/~ucdev/+archive/ubuntu/uc-staging-ppa.
> 
> Those binaries are there as of yesterday..

For focal... not for jammy. For jammy we have a good shim in the old PPA, I would like to upload a new one when we have shim 15.6 signed by Microsoft.

2023-02-23 17:17 UTC, alfonsosanchezbeato commented
Now that we have the jammy packages, I've rebased this PR.

2023-02-23 17:21 UTC, xnox approved these changes

2023-02-24 12:17 UTC, alfonsosanchezbeato commented
Somewhat gadgets built using shim/grub from latest in ucdev are failing for FDE, blocking the merge for the moment.

2023-02-24 13:14 UTC, valentindavid approved these changes

2023-02-28 15:44 UTC, xnox requested changes
Needs fixing in light of https://github.com/snapcore/pc-gadget/pull/81 getting merged

2023-02-28 17:00 UTC, alfonsosanchezbeato commented
> Needs fixing in light of #81 getting merged

Rebased now

2023-05-05 10:10 UTC, alfonsosanchezbeato commented
Updated by adding "assumes" cc @xnox

2023-05-10 08:16 UTC, merged